---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: dov-cm-bear

    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-pod
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
      namespace: myns
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: dov-port
          containerPort: 3000
        env:
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef: 
            name: dov-cm

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: LoadBalancer
  # type: ClusterIP
  # type: NodePort

  selector:
    name: dov-pod
  ports:
  - port: 8080
    targetPort: dov-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-ing
  labels:
    name: dov-ing
spec:
  ingressClassName: nginx
  rules:
  - host: dov-157.230.193.244.nip.io
    http: 
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dov-svc
            port: 
              number: 8080

    
