apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dov-bear/javascript

namePrefix: kuz-
nameSuffix: -k8s

commonLabels:
  deployDate: "Marc-31-2022"

replicas:
- name: dov-deploy
  count: 3