apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: mydb-svc.ws3.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---