apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  labels:
    name: dov-pod
  namespace: myns
spec:
  containers:
  - name: dov-container
    image: stackupiss/dov-bear:v2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
    env:
    - name: INSTANCE_NAME
      value: dov-bear
      name: INSTANCE_HASH
      valueFrom: 
        fieldRef:
          fieldPath: status.podIP
