---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: dov-cm-bear

    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-pod
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
      namespace: myns
    spec:
      containers:
      - name: dov-container
        image: stackupiss/dov-bear:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: dov-port
          containerPort: 3000
        env:
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef: 
            name: dov-cm
        resources:
          requests:
            cpu: 100m
            memory: 32Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: LoadBalancer
  # type: ClusterIP
  # type: NodePort

  selector:
    name: dov-pod
  ports:
  - port: 8080
    targetPort: dov-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-ing
  labels:
    name: dov-ing
spec:
  ingressClassName: nginx
  rules:
  - http: 
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dov-svc
            port: 
              number: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-hpa
  labels:
    name: dov-hpa
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-deploy
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
