version: '3'
volumes:
  new_vol:


networks:
  app_net:


services:
  db:
    image: stackupiss/northwind-db:v1
    volumes:
      - new_vol:/var/lib/mysql
    networks:
      - app_net

  app:
    image: stackupiss/northwind-app:v1
    ports:
      - 8080-9000:3000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - app_net