apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-app-data-pvc
    labels:
        name: wordpress-app-data-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: do-block-storage
    storage:
