apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db-secret
    labels:
      name: wordpress-db-secret
type: Opaque
data:
    WORDPRESS_DB_PASSWORD: cm9vdHJvb3Q=
    ROOT_PASSWORD: cm9vdHJvb3Q=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
    name: wordpress-mysql-cluster
    labels:
        name: wordpress-mysql-cluster
spec:
    replicas: 1
    secretName: wordpress-db-secret
    mysqlVersion: "8.0"
    volumeSpec:
        persistentVolumeClaim:
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: "1Gi"
            storageClassName: do-block-storage
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: wordpress-db
spec:
  database: wordpress-db
  clusterRef:
    name: wordpress-mysql-cluster